package main

const (
	TABLE_SIZE = 70
	PRIVATE_VECTOR_SIZE = 10
	TABLE_PRIME_SIZE = 8
	PRIVATE_VECTOR_PRIME_SIZE = 2
	E_VALUE = 11
	M_VALUE = 52
	NUM_INSTANCES = 256
	EVAL_MODE = "table1/2"
	ACTIVATION = "gelu"
	PROVING = false
	SIZE_VALUE = 16
)
